#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPO_FULL_NAME = "coreycoto/git-slop"
REPO_GIT_URL = f"https://github.com/{REPO_FULL_NAME}.git"
SEMVER = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")
REVISION = re.compile(r"^[0-9a-fA-F]{40,64}$")


def render_formula(manifest: dict[str, Any]) -> str:
    version, homebrew_source = validate_manifest(manifest)
    return (
        "class GitSlop < Formula\n"
        '  desc "Deterministic repository health analysis for humans and AI agents"\n'
        '  homepage "https://github.com/coreycoto/git-slop"\n'
        f'  url "{homebrew_source["url"]}",\n'
        f'      tag:      "{homebrew_source["tag"]}",\n'
        f'      revision: "{homebrew_source["revision"]}"\n'
        '  license "MIT"\n\n'
        '  depends_on "rust" => :build\n\n'
        "  def install\n"
        '    system "cargo", "install", *std_cargo_args\n'
        '    man1.install "man/git-slop.1"\n'
        "  end\n\n"
        "  test do\n"
        f'    assert_match "git-slop {version}", shell_output("#{{bin}}/git-slop version")\n'
        "  end\n"
        "end\n"
    )


def validate_manifest(manifest: dict[str, Any]) -> tuple[str, dict[str, str]]:
    if manifest.get("schema_version") != 2:
        raise ValueError("release manifest schema_version must be 2")
    if manifest.get("project") != "git-slop":
        raise ValueError("release manifest project must be git-slop")
    if manifest.get("repository") != REPO_FULL_NAME:
        raise ValueError(f"release manifest repository must be {REPO_FULL_NAME}")

    version = manifest.get("version")
    tag = manifest.get("tag")
    revision = manifest.get("revision")
    if not isinstance(version, str) or SEMVER.fullmatch(version) is None:
        raise ValueError("release manifest version must be strict semver")
    if tag != f"v{version}":
        raise ValueError("release manifest tag must agree with version")
    if not isinstance(revision, str) or REVISION.fullmatch(revision) is None:
        raise ValueError("release manifest revision must be a full commit id")

    source = manifest.get("homebrew_source")
    if not isinstance(source, dict):
        raise ValueError("release manifest must include homebrew_source")
    if source.get("url") != REPO_GIT_URL:
        raise ValueError(f"homebrew_source url must be {REPO_GIT_URL}")
    if source.get("tag") != tag:
        raise ValueError("homebrew_source tag must agree with the top-level tag")
    if source.get("revision") != revision:
        raise ValueError("homebrew_source revision must agree with the top-level revision")
    return version, {
        "url": REPO_GIT_URL,
        "tag": tag,
        "revision": revision,
    }


def _git_revision(tag: str) -> str:
    return subprocess.check_output(
        [
            "git",
            "rev-parse",
            "--verify",
            f"refs/tags/{tag}^{{commit}}",
        ],
        cwd=PROJECT_ROOT,
        text=True,
    ).strip()


def _manifest_from_args(args: argparse.Namespace) -> dict[str, Any]:
    if args.manifest:
        return json.loads((PROJECT_ROOT / args.manifest).read_text(encoding="utf-8"))
    if not args.tag or not args.version:
        raise ValueError("provide --manifest or both --tag and --version")
    revision = args.revision or _git_revision(args.tag)
    return {
        "schema_version": 2,
        "project": "git-slop",
        "repository": REPO_FULL_NAME,
        "version": args.version,
        "tag": args.tag,
        "revision": revision,
        "homebrew_source": {
            "url": REPO_GIT_URL,
            "tag": args.tag,
            "revision": revision,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Update the Homebrew formula for git-slop.")
    parser.add_argument(
        "--manifest",
        help="Release manifest generated by build_release_manifest.py.",
    )
    parser.add_argument("--tag", help="Release tag when no manifest is available.")
    parser.add_argument("--version", help="Release version when no manifest is available.")
    parser.add_argument("--revision", help="Exact release revision; defaults to the tag revision.")
    parser.add_argument(
        "--formula",
        default="../homebrew-tap/Formula/git-slop.rb",
        help="Formula path to write.",
    )
    args = parser.parse_args()

    manifest = _manifest_from_args(args)
    formula_path = (PROJECT_ROOT / args.formula).resolve()
    formula_path.parent.mkdir(parents=True, exist_ok=True)
    formula_path.write_text(render_formula(manifest), encoding="utf-8")
    print(formula_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
