from __future__ import annotations

import json
from pathlib import Path
from typing import Any

PROMPT_PACK_VERSION = 1


def _report_excerpt(report: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": report.get("schema_version"),
        "repo": report.get("repo", {}),
        "summary": report.get("summary", {}),
        "stats": report.get("stats", {}),
    }


def _prompt_for(command: str) -> str:
    return "\n".join(
        [
            f"# git-slop {command} prompt pack",
            "",
            "Use only the facts in context.json.",
            "",
            "Summarize the selected detector evidence for a maintainer. Keep hotspot",
            "costs separate from overlay evidence. Treat model output as advisory:",
            "do not rescore detector truth, claim correctness, or imply a refactor is",
            "mandatory. If the supplied facts are insufficient, say what is missing",
            "instead of inventing context.",
            "",
            "Preferred output:",
            "",
            "1. Brief maintainer summary",
            "2. Strongest evidence",
            "3. Suggested next review step",
            "4. Boundaries and non-claims",
            "",
        ]
    )


def _readme_for(command: str) -> str:
    return "\n".join(
        [
            f"# git-slop {command} Prompt Pack",
            "",
            "This directory was generated by git-slop for local model use.",
            "",
            "Files:",
            "",
            "- `context.json`: deterministic git-slop payload plus minimal report metadata.",
            "- `prompt.md`: prompt text for a local model.",
            "- `README.md`: these usage notes.",
            "",
            "Boundary rules:",
            "",
            "- This pack is advisory only.",
            "- Local model output must not mutate code, GitHub, or detector truth.",
            "- Local model output must not rescore detector truth, including",
            "  `slop_score`, `slop_band`,",
            "  `context_band`, or `git slop check` semantics.",
            "- Keep hotspot cost separate from overlay evidence.",
            "",
        ]
    )


def build_prompt_pack_context(
    *,
    command: str,
    payload: dict[str, Any],
    report: dict[str, Any],
) -> dict[str, Any]:
    return {
        "prompt_pack_version": PROMPT_PACK_VERSION,
        "command": command,
        "payload": payload,
        "report_excerpt": _report_excerpt(report),
        "boundary": (
            "Local model output is advisory only and must not rescore detector "
            "truth or mutate code, GitHub, or report data."
        ),
    }


def write_prompt_pack(
    *,
    command: str,
    payload: dict[str, Any],
    report: dict[str, Any],
    output_dir: Path,
) -> None:
    if output_dir.exists() and not output_dir.is_dir():
        raise ValueError(f"Prompt pack path is not a directory: {output_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)
    context = build_prompt_pack_context(command=command, payload=payload, report=report)
    (output_dir / "context.json").write_text(
        json.dumps(context, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (output_dir / "prompt.md").write_text(_prompt_for(command), encoding="utf-8")
    (output_dir / "README.md").write_text(_readme_for(command), encoding="utf-8")
