from __future__ import annotations

import json
from typing import Any

PLAN_SCHEMA_VERSION = 2
REFACTOR_PREVIEW_SCHEMA_VERSION = 1
BOUNDARY_NOTE = (
    "Refactor preview boundary: this is a deterministic, preview-only handoff "
    "from an existing git-slop plan. It does not mutate code, create patches, "
    "commit or push changes, invoke models, rescore detector truth, rerun the "
    "detector, or mutate GitHub."
)


def _validate_plan(plan: dict[str, Any]) -> None:
    if plan.get("command") != "plan":
        raise ValueError("git slop refactor-preview requires a git slop plan payload.")
    if plan.get("schema_version") != PLAN_SCHEMA_VERSION:
        raise ValueError(f"git slop refactor-preview requires plan schema {PLAN_SCHEMA_VERSION}.")
    if not isinstance(plan.get("proposed_slices"), list):
        raise ValueError("git slop refactor-preview requires proposed_slices in the plan payload.")


def _normalize_slice_ids(slice_ids: list[str] | None) -> list[str] | None:
    if slice_ids is None:
        return None
    normalized: list[str] = []
    for raw_value in slice_ids:
        for value in raw_value.split(","):
            clean = value.strip()
            if clean:
                normalized.append(clean)
    return normalized or None


def _select_slices(
    plan: dict[str, Any],
    *,
    slice_ids: list[str] | None = None,
) -> list[dict[str, Any]]:
    proposed_slices = plan.get("proposed_slices", [])
    if slice_ids is None:
        return list(proposed_slices)

    by_id = {item.get("id"): item for item in proposed_slices if isinstance(item.get("id"), str)}
    missing = [slice_id for slice_id in slice_ids if slice_id not in by_id]
    if missing:
        raise ValueError(f"Unknown plan slice id: {', '.join(missing)}")
    return [by_id[slice_id] for slice_id in slice_ids]


def _proposed_steps(slice_payload: dict[str, Any]) -> list[str]:
    scope = slice_payload.get("scope_paths", [])
    out_of_scope = slice_payload.get("out_of_scope_paths", [])
    return [
        "Read the scoped files and compare their current behavior before editing.",
        "Identify the smallest cohesive maintenance change supported by the cited evidence.",
        "Draft changes only inside the scoped paths unless new evidence is documented.",
        "Run the existing focused tests or add a narrow regression test before broad cleanup.",
        (
            "Leave these paths untouched in this pass: "
            + (", ".join(out_of_scope) if out_of_scope else "none")
        ),
        f"Keep the candidate scope bounded to {len(scope)} path(s).",
    ]


def _review_checklist(slice_payload: dict[str, Any]) -> list[str]:
    return [
        "Scope matches the plan slice and does not drift into unrelated files.",
        "The change is justified by the evidence summary, not by detector score alone.",
        "Detector priority_score, priority_band, and context_band semantics stay unchanged.",
        "Any follow-up work is documented separately instead of expanding this slice.",
    ]


def _patch_preview_notes(slice_payload: dict[str, Any]) -> list[str]:
    scope = slice_payload.get("scope_paths", [])
    return [
        "No patch is generated by git-slop.",
        "Use the scoped paths as the only default edit candidates.",
        (
            "A future patch should be reviewed against these paths: "
            + (", ".join(scope) if scope else "none")
        ),
        "Treat this preview as advisory maintenance planning, not an autonomous refactor loop.",
    ]


def _preview_slice(slice_payload: dict[str, Any]) -> dict[str, Any]:
    preview = {
        "id": slice_payload.get("id"),
        "title": slice_payload.get("title"),
        "maintainer_action": f"Preview bounded maintenance for {slice_payload.get('title')}.",
        "scope_paths": slice_payload.get("scope_paths", []),
        "out_of_scope_paths": slice_payload.get("out_of_scope_paths", []),
        "supporting_relationship_ids": slice_payload.get("supporting_relationship_ids", []),
        "supporting_cluster_ids": slice_payload.get("supporting_cluster_ids", []),
        "evidence_summary": slice_payload.get("evidence_summary"),
        "why_this_slice": slice_payload.get("why_this_slice"),
        "proposed_steps": _proposed_steps(slice_payload),
        "review_checklist": _review_checklist(slice_payload),
        "patch_preview_notes": _patch_preview_notes(slice_payload),
        "mutation_policy": "preview_only",
    }
    if "backlog_handoff" in slice_payload:
        preview["backlog_handoff"] = slice_payload["backlog_handoff"]
    return preview


def build_refactor_preview_payload(
    plan: dict[str, Any],
    *,
    plan_path: str | None = None,
    slice_ids: list[str] | None = None,
) -> dict[str, Any]:
    _validate_plan(plan)
    selected_slice_ids = _normalize_slice_ids(slice_ids)
    selected_slices = _select_slices(plan, slice_ids=selected_slice_ids)
    selected_ids = [item.get("id") for item in selected_slices]
    return {
        "schema_version": REFACTOR_PREVIEW_SCHEMA_VERSION,
        "report_schema_version": plan.get("report_schema_version"),
        "command": "refactor-preview",
        "mutation_policy": "preview_only",
        "source_plan": {
            "schema_version": plan.get("schema_version"),
            "path": plan_path,
            "selector": plan.get("selector"),
            "target": plan.get("target"),
            "selected_slice_ids": selected_ids,
            "boundary_note": plan.get("boundary_note"),
        },
        "preview_slices": [_preview_slice(slice_payload) for slice_payload in selected_slices],
        "boundary_note": BOUNDARY_NOTE,
    }


def _render_paths(paths: list[str]) -> str:
    return ", ".join(paths) if paths else "none"


def _render_ids(ids: list[str]) -> str:
    return ", ".join(ids) if ids else "none"


def _render_steps(label: str, steps: list[str]) -> list[str]:
    lines = [f"   {label}:"]
    lines.extend(f"   - {step}" for step in steps)
    return lines


def render_refactor_preview_text(payload: dict[str, Any]) -> str:
    source_plan = payload.get("source_plan", {})
    target = source_plan.get("target", {}) or {}
    selector = source_plan.get("selector", {}) or {}
    target_label = target.get("path") or target.get("id") or selector.get("value") or "unknown"
    lines = [f"Refactor Preview: {target_label}"]
    lines.append(f"mutation_policy: {payload.get('mutation_policy')}")
    for index, slice_payload in enumerate(payload.get("preview_slices", []), start=1):
        lines.extend(
            [
                "",
                f"{index}. {slice_payload.get('title')}",
                f"   maintainer_action: {slice_payload.get('maintainer_action')}",
                f"   scope: {_render_paths(slice_payload.get('scope_paths', []))}",
                f"   out_of_scope: {_render_paths(slice_payload.get('out_of_scope_paths', []))}",
                f"   evidence_summary: {slice_payload.get('evidence_summary')}",
                (
                    "   evidence: "
                    "relationships="
                    f"{_render_ids(slice_payload.get('supporting_relationship_ids', []))}; "
                    f"clusters={_render_ids(slice_payload.get('supporting_cluster_ids', []))}"
                ),
            ]
        )
        lines.extend(_render_steps("proposed_steps", slice_payload.get("proposed_steps", [])))
        lines.extend(
            _render_steps("review_checklist", slice_payload.get("review_checklist", []))
        )
        lines.extend(
            _render_steps("patch_preview_notes", slice_payload.get("patch_preview_notes", []))
        )
    lines.extend(["", payload["boundary_note"]])
    return "\n".join(lines)


def render_refactor_preview_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"
